title: Luisa Velasco
logo: /assets/img/logo.png
description: I am a first year PhD student interested in mathematical physics and analysis at the University of Texas at Austin.[[CV]](./CV_3_25_2023.pdf)    [[Preprints & Publications]](./papers.html)

show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
