title: Luisa Velasco
logo: /assets/img/logo.png
description: I am a first year PhD student interested in mathematical physics and analysis at the University of Texas at Austin.  
office: Office: PMA 12.146
email: lmvelasco@utexas.edu
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
