title: Luisa Velasco
logo: /assets/img/me.png
description: I am a second year PhD student interested in mathematical physics, analysis and probability at the University of Texas at Austin.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
